# version: '3'
# 启动 docker-compose --env-file=.env up
# 如果需要konga，参考konga.md
# depends_on只是要求服务A必须早于服务B启动，但并不是说A启动完成后才启动B
# 所以kong启动刚开始可能报错，但会不断重启，直到kong-migrations启动完成
# 建议按照kong.md手动跑一遍，容易理解
version: '3.9'
networks:
  local:
    driver: bridge

services:
  pgsql:
    image: "postgres:9.6"
    container_name: pgsql
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    networks:
      - local
    ports:
      - 5432:5432

    restart: on-failure
  
  consul_server:
    image: consul:latest
    container_name: consul_server
    networks:
      - local
    ports:
      - 8500:8500
      #- 8600:8600/udp #consul 8600 需要udp通信
      - 53:53/udp #dns服务器端口 53 需要udp通信
    command: agent -server=true -client=0.0.0.0 --bootstrap-expect=1 --node=leader -dns-port=53 -ui

  kong-migrations:
    image: "kong:${TAG}"
    container_name: kong-migrations
    command: kong migrations bootstrap --vv
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: ${POSTGRES_IP}
      KONG_PG_PASSWORD: kong
    depends_on:
      - pgsql
      - consul_server
    restart: on-failure

  kong:
    image: "kong:${TAG}"
    container_name: kong
    environment:
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PG_HOST: ${POSTGRES_IP}
      KONG_DATABASE: postgres
      KONG_PG_PASSWORD: kong
      KONG_ADMIN_LISTEN: 0.0.0.0:8510
      KONG_PROXY_LISTEN: 0.0.0.0:8508 http2,0.0.0.0:8509
      KONG_DNS_RESOLVER: ${CONSUL_IP}:53
    networks:
      - local
    ports:
      - 8508:8508
      - 8509:8509
      - 8510:8510
    volumes:
      - ./proto:/proto #挂载proto文件，与kong_init.sh中grpc_web配置相关
    depends_on:
      - kong-migrations
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
    restart: on-failure

  hello:
    image: hello:test
    container_name: hello
    networks:
      - local
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - ./configs:/data/conf
    

  konga:
    image: "pantsel/konga:latest"
    container_name: konga
    environment:
      - DB_ADAPTER=postgres
      - DB_HOST=${POSTGRES_IP}
      - DB_USER=kong
      - DB_PASSWORD=kong
      - DB_DATABASE=konga
    networks:
      - local
    ports:
      - 1337:1337
    depends_on:
      - pgsql
    restart: on-failure
